---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: x1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
      - name: busybox
        image: yauritux/busybox-curl
        command: ["sleep", "9600"]
---
apiVersion: v1
kind: Service
metadata:
  name: svc-service-a
  labels:
  namespace: x1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: y1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
      - name: busybox
        image: yauritux/busybox-curl
        command: ["sleep", "9600"]
---
apiVersion: v1
kind: Service
metadata:
  name: svc-service-b
  labels:
  namespace: y1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: service-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  namespace: z1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: service-c
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
      - name: busybox
        image: yauritux/busybox-curl
        command: ["sleep", "9600"]
---
apiVersion: v1
kind: Service
metadata:
  name: svc-service-c
  labels:
  namespace: z1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: service-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
  namespace: z1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-d
  template:
    metadata:
      labels:
        app: service-d
    spec:
      containers:
      - name: service-d
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
      - name: busybox
        image: yauritux/busybox-curl
        command: ["sleep", "9600"]
---
apiVersion: v1
kind: Service
metadata:
  name: svc-service-d
  labels:
  namespace: z1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: service-d